---

env: ${LOG_ENV}
sql:
  enabled: true
  driver: ${SQL_DRIVER}
  hostname: ${SQL_HOSTNAME}
  username: ${SQL_USERNAME}
  password: ${SQL_PASSWORD}
  database: ${SQL_DATABASE}
  port: ${SQL_PORT}
  prefix: ${SQL_PREFIX}
mongo:
  enabled: true
  host: ${MONGO_HOST}
  port: ${MONGO_PORT}
  user: ${MONGO_USER}
  password: ${MONGO_PASSWORD}
  database: ${MONGO_DATABASE}
  expired_days: 90
telegram:
  enabled: true
  api_key: ${TELEGRAM_API_KEY}
  admin_id: ${TELEGRAM_ADMIN_ID}
  bot_name: Zoho Client
  min_log_level: debug
zoho:
  client_id: ${ZOHO_CLIENT_ID}
  client_secret: ${ZOHO_CLIENT_SECRET}
  refresh_token: ${ZOHO_REFRESH_TOKEN}
  refresh_url: ${ZOHO_REFRESH_URL}
  crm_url: ${ZOHO_CRM_URL}
  scope: crm
  api_version: v8
prod_repo:
  login: ${REPO_LOGIN}
  password: ${REPO_PASSWORD}
  prod_url: ${REPO_PROD_URL}
listen:
  bind_ip: 127.0.0.1
  port: ${LISTEN_PORT}
  key: ${API_KEY}
smartsender:
  enabled: false
  api_key: ${SMARTSENDER_API_KEY}
  base_url: https://api.smartsender.com/v1
  zoho_api_key: ${ZOHO_API_KEY}
  zoho_msg_url: https://www.zohoapis.eu/crm/v7/functions/getmessagefromsmartsender/actions/execute
  zoho_task_url: https://www.zohoapis.eu/crm/v7/functions/createtask/actions/execute
  poll_interval: 60
