name: Deploy to wattbrews.me with tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Check if tag exists
        run: |
          git fetch --all --tags
          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
            exit 1
          fi

      - name: Prepare configuration file
        run: |
          sed -i 's|${LOG_ENV}|'"$LOG_ENV"'|g' zohoclient-config.yml
          sed -i 's|${LISTEN_PORT}|'"$LISTEN_PORT"'|g' zohoclient-config.yml
          sed -i 's|${API_KEY}|'"$API_KEY"'|g' zohoclient-config.yml
          sed -i 's|${SQL_DRIVER}|'"$SQL_DRIVER"'|g' zohoclient-config.yml
          sed -i 's|${SQL_HOSTNAME}|'"$SQL_HOSTNAME"'|g' zohoclient-config.yml
          sed -i 's|${SQL_USERNAME}|'"$SQL_USERNAME"'|g' zohoclient-config.yml
          sed -i 's|${SQL_PASSWORD}|'"$SQL_PASSWORD"'|g' zohoclient-config.yml
          sed -i 's|${SQL_DATABASE}|'"$SQL_DATABASE"'|g' zohoclient-config.yml
          sed -i 's|${SQL_PORT}|'"$SQL_PORT"'|g' zohoclient-config.yml
          sed -i 's|${SQL_PREFIX}|'"$SQL_PREFIX"'|g' zohoclient-config.yml
          sed -i 's|${TELEGRAM_API_KEY}|'"$TELEGRAM_API_KEY"'|g' zohoclient-config.yml
          sed -i 's|${ZOHO_CLIENT_ID}|'"$ZOHO_CLIENT_ID"'|g' zohoclient-config.yml
          sed -i 's|${ZOHO_CLIENT_SECRET}|'"$ZOHO_CLIENT_SECRET"'|g' zohoclient-config.yml
          sed -i 's|${ZOHO_REFRESH_TOKEN}|'"$ZOHO_REFRESH_TOKEN"'|g' zohoclient-config.yml
          sed -i 's|${ZOHO_REFRESH_URL}|'"$ZOHO_REFRESH_URL"'|g' zohoclient-config.yml
          sed -i 's|${ZOHO_CRM_URL}|'"$ZOHO_CRM_URL"'|g' zohoclient-config.yml
          sed -i 's|${REPO_LOGIN}|'"$REPO_LOGIN"'|g' zohoclient-config.yml
          sed -i 's|${REPO_PASSWORD}|'"$REPO_PASSWORD"'|g' zohoclient-config.yml
          sed -i 's|${REPO_PROD_URL}|'"$REPO_PROD_URL"'|g' zohoclient-config.yml
        env:
          LOG_ENV: ${{ vars.LOG_ENV }}
          SQL_DRIVER: ${{ vars.SQL_DRIVER }}
          SQL_HOSTNAME: ${{ vars.SQL_HOSTNAME }}
          SQL_USERNAME: ${{ vars.SQL_USERNAME }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_DATABASE: ${{ vars.SQL_DATABASE }}
          SQL_PORT: ${{ vars.SQL_PORT }}
          SQL_PREFIX: ${{ vars.SQL_PREFIX }}
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          ZOHO_CLIENT_ID: ${{ secrets.ZOHO_CLIENT_ID }}
          ZOHO_CLIENT_SECRET: ${{ secrets.ZOHO_CLIENT_SECRET }}
          ZOHO_REFRESH_TOKEN: ${{ secrets.ZOHO_REFRESH_TOKEN }}
          ZOHO_REFRESH_URL: ${{ vars.ZOHO_REFRESH_URL }}
          ZOHO_CRM_URL: ${{ vars.ZOHO_CRM_URL }}
          REPO_LOGIN: ${{ secrets.REPO_LOGIN }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
          REPO_PROD_URL: ${{ vars.REPO_PROD_URL }}

      - name: Copy Configuration to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "zohoclient-config.yml"
          target: "/etc/conf"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go application
        run: |
          go build -v -o zohoclient ./cmd/zoho

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "zohoclient"
          target: "/usr/local/bin/"

      - name: Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            systemctl restart zohoclient.service